### ISSUE TITLE
question about proofpurpose.

### ISSUE THREAD

**Issue by picardcapt1212** [digitalbazaar/jsonld-signatures#144]
Hello, i have a question about proofpurpose.

I'm trying to issue verifiable credential and verifiable presentation.

When i checked W3C vc data model, assertionMethod(for verifiable credential) and authentication(for verifiable presentation) were used for issuing.

As i'm using jsonld-signatures package, i wondered why the proofpurpose only has AssertionProofPurpose and AuthenticationProofPurpose.

Is there a reason why keyAgreement, capabilityDelegation, capablityInvocation is not used for proofpurpose?

Looking forward to your reply. 

Thank you.

**Comment by mattcollier** [comment]
I think you'll find the code and documentation here helpful: https://github.com/digitalbazaar/vc-js

**Comment by picardcapt1212** [comment]
Thank you for reply!

I've seen vc-js repo, but i still can't find any other proofpurposes.

In vc-js, what i saw was only `AuthenticationProofPurpose` and `AssertionProofPurpose`. (Or did i not find the right code?)

Can I get where the `proofpurpose` usage part is? 
Or am i understanding it wrong? issuing vc/vp should only use assertionMethod, authentication?

Thanks!

**Comment by dlongley** [comment]
@picardcapt1212,

Other function-specific libraries that use jsonld-signatures provide the other proof purposes. For example, for creating proofs for the purpose of `capabilityInvocation` or `capabilityDelegation`, the ZCAP-LD library [zcapld](https://github.com/digitalbazaar/zcapld) can be used, see: [capabilityInvocation](https://github.com/digitalbazaar/zcapld/blob/main/lib/CapabilityInvocation.js) and [capabilityDelegation](https://github.com/digitalbazaar/zcapld/blob/main/lib/CapabilityDelegation.js) extensions for the specific proof purpose implementations.

> issuing vc/vp should only use assertionMethod, authentication?

Yes, a VC should typically only be signed for the purpose of making an assertion and a VP should typically only be signed for the purpose of authentication. It would be mixing purposes to sign a VC or a VP to take an action (invoke a capability) or delegate an action (delegate a capability). VCs are signed for making claims (a method of assertion) and VPs are signed for authenticating.

The point of proof purposes is to ensure that a verifier can understand the signer's intent when verifying. It makes it so that if you signed something to merely make a claim (proof purpose `assertionMethod`) -- it could not be confused with an attempt to authenticate (proof purpose `authentication`) or to take an action (proof purpose `capabilityInvocation`).

Otherwise, someone could potentially take a VC that you signed and that you intended to be shared -- and use it on a confused verifier to authenticate as you or to take an action as you. This was not your intent.

**Comment by picardcapt1212** [comment]
Okay now I get it.
I really appreciated your reply! :)
