### ISSUE TITLE
Design and implement EdDSA signature suite

### ISSUE THREAD

**Issue by msporny** [digitalbazaar/jsonld-signatures#21]
@tarcieri wrote:
> New protocols should NOT be using ECDSA. ECDSA has repeatedly failed in practice, has many failure modes modern signature schemes are not vulnerable to, and now that the Schnorr patents have expired is completely obsolete. 
> In all of my personal and professional work we are using EdDSA, which is a Schnorr scheme and standardized in RFC 8032.

We've had multiple requests for supporting EdDSA, specifically Ed25519. To implement this, we'd need an implementation of it in https://github.com/digitalbazaar/forge/ and then a simple signature suite to use it in the Linked Data Signatures spec.

**Comment by tarcieri** [comment]
Just for the record (since this issue came up via the VC mailing list) I have nothing against secp256k1 when used for signatures, or Blockstream's secp256k1 Schnorr scheme (except for lack of standardization around it). My complaints are squarely with ECDSA.

The nice thing about EdDSA is it's standardized in RFC 8032. I hope Blockstream will work with the CFRG or some other cryptography standards body to publish some standards around their secp256k1 Schnorr scheme (and perhaps give it a catchy name so I can stop calling it "Blockstream's secp256k1 Schnorr scheme")

**Comment by krobi64** [comment]
Now that Ed25519 is available in forge, is this on the roadmap?

**Comment by krobi64** [comment]
Thanks

**Comment by dmitrizagidulin** [comment]
Closing this issue, since support for `Ed25519Signature2018` has been implemented. If other EdDSA algorithms are required to be supported, we can open a separate issue for each.
