### ISSUE TITLE
Can't resolve 'bitcore-lib'

### ISSUE THREAD

**Issue by kezike** [digitalbazaar/jsonld-signatures#58]
I have been using `jsonld-signatures` for a project I have been working on for some time now. It has involved signing and verifying documents in the browser and has been working fine for a while. However, I recently noticed that when I pull a new instance of my repo to test out the experience of a new user, I am running into the following error at launch time:

```
ERROR in ./node_modules/jsonld-signatures/node_modules/bitcore-message/lib/message.js
Module not found: Error: Can't resolve 'bitcore-lib' in './node_modules/jsonld-signatures/node_modules/bitcore-message/lib'
```

I am wondering if this is a relatively new issue attributed to any recent changes made by the team or if anyone else has come across an issue like this. I am willing to share more details and potentially even the project repo for those that are interested in exploring this problem and desire more context.

**Comment by davidlehn** [comment]
Looks like it's working for me.  I see a deep dependency path.  Is that an older version of npm?  Newer versions have a flatter structure.  Have you just tried a fresh install to see if the dependencies get setup properly?  Could also check your node_modules tree for bitcore-lib since it should be installed somewhere.

There have been many recent changes, but the tests keep running so at least they are able to load that modules.

**Comment by kezike** [comment]
It turns out that re-installing did indeed fix things, but it's strange that I would have to do that. I included `npm install` in an installation script, but that installation doesn't properly install things. So I had to explicitly add another line just for installing `jsonld-signatures`, which seems superfluous.

**Comment by dmitrizagidulin** [comment]
Closing this issue, since it sounds like it's been resolved (please feel free to reopen if you run into it again).
